services:

  shell: &shell
    build: .
    entrypoint: "sh"

  client:
    <<: *shell
    entrypoint: "/bin/zig-memstore-client 10.5.0.1:9876"

  server:
    <<: *shell
    entrypoint: "/bin/zig-memstore 9876"
    ports:
      - "9876:9876"
