services:

  shell:
    build:
      context: .
      target: build
    entrypoint: "zsh"

  client:
    build: .
    entrypoint: "/bin/zig-memstore-client 10.5.0.1:9876"

  server:
    build: .
    entrypoint: "/bin/zig-memstore 9876"
    ports:
      - "9876:9876"
